Repository FiveIT/eseuri, pull requests merged in 2021-04, with the labels that each got.

#42 Add classes not compiled on Windows to safelist
  web/windi.config.ts
Labels: bug

#45 Integrate GraphQL with client and implement work summaries fetching
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .editorconfig
  web/package.json
  web/pnpm-lock.yaml
  web/src/App.svelte
  web/src/components/BookmarkButton.svelte
  web/src/components/Layout.svelte
  web/src/components/LayoutContext.svelte
  web/src/components/Link.svelte
  web/src/components/LoginButton.svelte
  web/src/components/NavButton.svelte
  web/src/components/SearchBar.svelte
  web/src/components/SlimNav.svelte
  web/src/components/TypeSelector.svelte
  web/src/components/UploadButton.svelte
  web/src/components/Work.svelte
  web/src/components/Works.svelte
  web/src/content.ts
  web/src/graphql/client.ts
  web/src/graphql/queries.ts
  web/src/graphql/types.ts
  web/src/pages/essays/[page_name].svelte
  web/src/pages/index.svelte
  web/src/pages/register.svelte
  web/src/pages/search.svelte
  web/src/pages/upload_configure.svelte
  web/src/types.ts
  web/tsconfig.json
  web/vite.config.ts
Labels: Functionality

#48 Notification component
  web/src/components/Notification.svelte
  web/src/components/Notifications.svelte
  web/src/graphql/queries.ts
  web/src/graphql/types.ts
  web/src/pages/index.svelte
  web/src/pages/register.svelte
  web/src/pages/search.svelte
  web/src/style.css
  web/src/theme.ts
  web/windi.config.ts
Labels: Frontend
